# Generated by Django 6.0.2 on 2026-02-23 11:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Формат: +420XXXXXXXXX', max_length=20, unique=True, verbose_name='Номер телефону')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Прізвище')),
                ('roles', models.JSONField(default=list, help_text='Масив ролей: PASSENGER, DRIVER, DISPATCHER', verbose_name='Ролі')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Офлайн')], default='OFFLINE', max_length=10, verbose_name='Статус')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Кількість поїздок')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Загальний заробіток (Kč)')),
                ('current_lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('current_lng', models.FloatField(blank=True, null=True, verbose_name='Довгота')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль водія',
                'verbose_name_plural': 'Профілі водіїв',
            },
        ),
    ]
