# Generated by Django 6.0.2 on 2026-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Формат: +380XXXXXXXXX",
                max_length=20,
                unique=True,
                verbose_name="Номер телефону",
            ),
        ),
    ]
