# Generated by Django 6.0.2 on 2026-04-20 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Відсоток прийнятих замовлень від загальної кількості",
                        max_digits=5,
                        verbose_name="Швидкість прийняття (%)",
                    ),
                ),
                (
                    "avg_response_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Середній час відповіді (с)",
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Агрегований скор для визначення пріоритету",
                        max_digits=5,
                        verbose_name="Композитний скор",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to="accounts.driverprofile",
                        verbose_name="Водій",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ранкінг водія",
                "verbose_name_plural": "Ранкінги водіїв",
                "ordering": ["-composite_score"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kyc/id_cards/",
                        verbose_name="Посвідчення особи",
                    ),
                ),
                (
                    "license",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kyc/licenses/",
                        verbose_name="Водійське посвідчення",
                    ),
                ),
                (
                    "registration",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kyc/registrations/",
                        verbose_name="Реєстрація транспорту",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "На перевірці"),
                            ("APPROVED", "Затверджено"),
                            ("REJECTED", "Відхилено"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Статус верифікації",
                    ),
                ),
                (
                    "feedback_note",
                    models.TextField(
                        blank=True,
                        help_text="Причина відхилення або додаткова інформація",
                        verbose_name="Коментар модератора",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подано"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Перевірено"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to="accounts.driverprofile",
                        verbose_name="Водій",
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC документ",
                "verbose_name_plural": "KYC документи",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
