# Generated by Django 6.0.2 on 2026-03-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_vehicle_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["-id"],
                "verbose_name": "Автомобіль",
                "verbose_name_plural": "Автомобілі",
            },
        ),
    ]
