# Generated by Django 6.0.2 on 2026-02-23 11:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.CharField(max_length=300, verbose_name='Адреса подачі')),
                ('dropoff_address', models.CharField(max_length=300, verbose_name='Адреса призначення')),
                ('pickup_lat', models.FloatField(verbose_name='Широта подачі')),
                ('pickup_lng', models.FloatField(verbose_name='Довгота подачі')),
                ('dropoff_lat', models.FloatField(verbose_name='Широта призначення')),
                ('dropoff_lng', models.FloatField(verbose_name='Довгота призначення')),
                ('pickup_time', models.DateTimeField(verbose_name='Час подачі')),
                ('required_class', models.CharField(choices=[('ECONOMY', 'Економ'), ('PREMIUM', 'Комфорт'), ('MINIVAN', 'Мінівен')], default='ECONOMY', max_length=10, verbose_name='Клас авто')),
                ('is_pet_friendly', models.BooleanField(default=False, verbose_name='З тваринами')),
                ('needs_child_seat', models.BooleanField(default=False, verbose_name='Дитяче крісло')),
                ('needs_wheelchair_access', models.BooleanField(default=False, verbose_name='Інвалідний візок')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує'), ('ACCEPTED', 'Прийнято'), ('EN_ROUTE', 'В дорозі до клієнта'), ('IN_PROGRESS', 'Поїздка'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Скасовано')], default='PENDING', max_length=15, verbose_name='Статус')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Орієнтовна ціна (Kč)')),
                ('route_polyline', models.TextField(blank=True, help_text='Encoded polyline від Google Directions API', verbose_name='Polyline маршруту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Прийнято о')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено о')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to='accounts.driverprofile', verbose_name='Водій')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пасажир')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Від 1 до 5', verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_complaint', models.BooleanField(default=False, verbose_name='Це скарга?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Замовлення')),
                ('target_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.driverprofile', verbose_name='Водій')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
