# Generated by Django 6.0.2 on 2026-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_required_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="passenger_dismissed_rating",
            field=models.BooleanField(
                default=False,
                help_text="True якщо пасажир скасував оцінку без відгуку",
                verbose_name="Оцінку пропущено",
            ),
        ),
    ]
