# Generated by Django 6.0.2 on 2026-04-20 21:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_driverranking_kycdocument"),
        ("orders", "0003_order_passenger_dismissed_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наприклад: Аеропорт Вацлава Гавела",
                        max_length=100,
                        unique=True,
                        verbose_name="Назва зони",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Широта центру зони")),
                ("lng", models.FloatField(verbose_name="Довгота центру зони")),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=2000, verbose_name="Радіус геозони (м)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Віртуальна черга",
                "verbose_name_plural": "Віртуальні черги",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="calculated_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Розрахована відстань (км)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="commission_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Комісія платформи (Kč)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="upfront_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фінальна зафіксована ціна, показана до підтвердження",
                max_digits=8,
                null=True,
                verbose_name="Фіксована ціна (Kč)",
            ),
        ),
        migrations.CreateModel(
            name="VirtualQueueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Позиція в черзі"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Вступив у чергу"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="accounts.driverprofile",
                        verbose_name="Водій",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="orders.virtualqueue",
                        verbose_name="Черга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис у черзі",
                "verbose_name_plural": "Записи у черзі",
                "ordering": ["position"],
                "unique_together": {("queue", "driver")},
            },
        ),
    ]
