# Generated by Django 6.0.2 on 2026-04-21 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_virtualqueue_order_calculated_distance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PASSENGER_REQUEST", "Пасажир скасував"),
                            ("DRIVER_REQUEST", "Водій скасував"),
                            ("NO_DRIVERS", "Таймаут — водії не знайдені"),
                            ("DISPATCHER_OVERRIDE", "Диспетчер скасував"),
                            ("SYSTEM", "Системне скасування"),
                        ],
                        default="PASSENGER_REQUEST",
                        max_length=25,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="Додаткова інформація"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Сума повернення (Kč)",
                    ),
                ),
                (
                    "refund_processed",
                    models.BooleanField(
                        default=False, verbose_name="Повернення оброблено"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Скасовано"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хто скасував",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_log",
                        to="orders.order",
                        verbose_name="Замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог скасування",
                "verbose_name_plural": "Логи скасувань",
                "ordering": ["-cancelled_at"],
            },
        ),
    ]
